
SELECT TRANSACTION_ID, TRANSACTION_TIME,
  CASE
      WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '12:00:00' THEN 'MORNING'
      WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '17:00:00' THEN 'AFTERNOON'
      ELSE 'EVENING'
END AS TIME_BUCKET,
TRANSACTION_DATE,
DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
 CASE
     WHEN DAYNAME(TRANSACTION_DATE) IN ('Sun', 'Sat') THEN 'WEEKEND'
 ELSE 'WEEKDAY'
END AS DAY_CLASSIFICATION,
MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME,  
COUNT (DISTINCT TRANSACTION_ID) AS NUMBER_OF_SALES,
SUM(TRANSACTION_QTY*UNIT_PRICE) AS REVENUE,
TRANSACTION_QTY,
CASE
      WHEN TRANSACTION_QTY >= 2 THEN 'MOST SOLD'
      ELSE 'LEAST SOLD'
END AS RANKING, 
PRODUCT_CATEGORY,
PRODUCT_DETAIL,
PRODUCT_TYPE,
STORE_LOCATION,
FROM PRODUCT_SALES
GROUP BY ALL
